pip install mxnet &&
pip install gluonnlp==0.9.1 &&
pip install sentencepiece &&
pip install transformers &&
pip install torch &&
pip install selenium &&
pip install bs4 &&
pip install webdriver_manager &&
pip install webdrivermanager &&
pip install BeautifulSoup &&
pip install 'git+https://github.com/SKTBrain/KoBERT.git#egg=kobert_tokenizer&subdirectory=kobert_hf' &&
pip install openpyxl &&